# Generated by Django 3.1 on 2020-12-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'managed': False},
        ),
    ]
