# Generated by Django 3.1 on 2020-12-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201217_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'managed': True},
        ),
    ]
