# Generated by Django 3.1 on 2020-12-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201217_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'managed': True, 'verbose_name_plural': 'branches'},
        ),
    ]
